# Generated by Django 2.2.6 on 2019-10-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='raw/')),
                ('ascii_characters', models.CharField(blank=True, max_length=200, null=True)),
                ('filters', models.IntegerField(choices=[(1, 'Average'), (2, 'Lightness'), (3, 'Luminosity')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AsciiImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='converted/')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw', to='app_converter.RawImage')),
            ],
        ),
    ]
