# Generated by Django 2.2.6 on 2019-10-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='converted/')),
            ],
        ),
    ]
