# Generated by Django 2.2.6 on 2019-10-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_converter', '0002_convertedimagefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConvertedImageFile',
        ),
    ]
