# Generated by Django 2.2.6 on 2019-10-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_converter', '0005_auto_20191013_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asciiimage',
            name='ascii_characters',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
