# Generated by Django 2.2.6 on 2019-10-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_converter', '0006_auto_20191013_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asciiimage',
            name='ascii_characters',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
