# Generated by Django 2.2.6 on 2019-10-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_converter', '0007_auto_20191013_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='raw/')),
            ],
        ),
        migrations.AddField(
            model_name='asciiimage',
            name='raw',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='raw', to='app_converter.RawImage'),
            preserve_default=False,
        ),
    ]
