# Generated by Django 2.2.6 on 2019-10-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_converter', '0008_auto_20191013_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asciiimage',
            name='raw',
        ),
        migrations.AddField(
            model_name='rawimage',
            name='ascii_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ascii_image', to='app_converter.AsciiImage'),
        ),
        migrations.AlterField(
            model_name='asciiimage',
            name='image',
            field=models.ImageField(upload_to='converted/'),
        ),
    ]
