# Generated by Django 2.2.6 on 2019-10-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_converter', '0009_auto_20191013_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asciiimage',
            name='ascii_characters',
        ),
        migrations.RemoveField(
            model_name='rawimage',
            name='ascii_image',
        ),
        migrations.AddField(
            model_name='asciiimage',
            name='raw',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='raw', to='app_converter.RawImage'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ascii_characters', models.CharField(blank=True, max_length=200, null=True)),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_setting', to='app_converter.RawImage')),
            ],
        ),
    ]
