# Generated by Django 2.2.6 on 2019-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_converter', '0010_auto_20191013_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawimage',
            name='ascii_characters',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ImageSetting',
        ),
    ]
