# Generated by Django 2.2.6 on 2019-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_converter', '0011_auto_20191014_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawimage',
            name='filters',
            field=models.IntegerField(choices=[('average', 'Average'), ('lightness', 'Lightness'), ('luminosity', 'Luminosity')], default=1),
        ),
    ]
