# Generated by Django 2.2.6 on 2019-10-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_converter', '0012_rawimage_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawimage',
            name='filters',
            field=models.IntegerField(choices=[(1, 'Average'), (2, 'Lightness'), (3, 'Luminosity')], default=1),
        ),
    ]
